# Generated by Django 4.2.2 on 2023-07-24 17:02

import blogzine.utils.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=50, validators=[blogzine.utils.validators.validate_alphabet_characters_english, django.core.validators.MinLengthValidator(5)])),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('question', 'Question'), ('poll', 'Poll'), ('images', 'Images'), ('video', 'Video'), ('other', 'Other')], max_length=20)),
                ('short_description', models.CharField(max_length=200, validators=[blogzine.utils.validators.validate_alphabet_characters_english, django.core.validators.MinLengthValidator(10)])),
                ('post_body', models.CharField(max_length=20, validators=[blogzine.utils.validators.validate_alphabet_characters_english])),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('lifestyle', 'Lifestyle'), ('technology', 'Technology'), ('travel', 'Travel'), ('business', 'Business'), ('sports', 'Sports'), ('marketing', 'Marketing')], max_length=50, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussion',
                'ordering': ['created_on'],
            },
        ),
    ]
