# Generated by Django 4.2.2 on 2023-07-24 18:56

import blogzine.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='post_body',
            field=models.TextField(max_length=20, validators=[blogzine.utils.validators.validate_alphabet_characters_english]),
        ),
    ]
