# Generated by Django 4.2.3 on 2023-08-11 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0007_alter_createpost_author'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='CommentPost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_post.createpost'),
            preserve_default=False,
        ),
    ]
