# Generated by Django 4.2.3 on 2023-08-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_post_comment_commentpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='CommentPost',
            new_name='post',
        ),
    ]
