# Generated by Django 4.2.3 on 2023-08-05 15:27

import blogzine.utils.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_alter_createpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='post_body',
            field=models.CharField(max_length=20, validators=[blogzine.utils.validators.validate_alphabet_characters_english]),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='short_description',
            field=models.TextField(max_length=200, validators=[blogzine.utils.validators.validate_alphabet_characters_english, django.core.validators.MinLengthValidator(10)]),
        ),
    ]
