# Generated by Django 4.2.3 on 2023-08-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_post_comment_commentpost'),
        ('blog_post', '0007_alter_createpost_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
